version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.9  # AWS SAM requires Python

    commands:

      - echo "Creating Lambda Layer dynamically..."
      - mkdir -p lambda-layer/nodejs/

      - cd lambda-layer/nodejs && npm init -y && npm install axios && cd ../..

      - cd lambda-layer && zip -r layer.zip nodejs && cd ..
    
      - echo "Checking if AWS SAM is installed..."
      - |
        if ! command -v sam &> /dev/null; then
          echo "AWS SAM not found. Installing..."
          pip install aws-sam-cli 
        else
          echo "AWS SAM is already installed."
        fi

          
      - aws s3 cp lambda-layer/layer.zip s3://$S3_BUCKET/lambda-layers/  

  pre_build:
    commands:
      - echo "========================================="
      - echo "Using Environment Variables from CodeBuild"
      - echo "========================================="
      - env | sort
      - echo "========================================="
      - echo "Checking if S3 bucket exists..."
      - |
       if ! aws s3 ls "s3://$S3_BUCKET" 2>/dev/null; then
         echo "S3 bucket $S3_BUCKET does not exist. Creating..."
         aws s3 mb "s3://$S3_BUCKET" --region "$REGION"
       else
         echo "S3 bucket $S3_BUCKET already exists."
       fi

  build:
    commands:
      - echo $S3_BUCKET
      - echo "Storing the template to S3..."
      - |
        sam package \
          --template-file $TEMPLATE_FILE \
          --s3-bucket $S3_BUCKET \
          --region $REGION

  post_build:
    commands:
      - echo "Deploying application..."
      - |
        sam deploy \
          --template-file $TEMPLATE_FILE \
          --stack-name $STACK_NAME \
          --s3-bucket $S3_BUCKET \
          --region $REGION \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM \
          --parameter-overrides \
            ApiStageName=$STAGE \
            DynamoDBTableName=$DYNAMODB_TABLE_NAME \
            LambdaFunctionName=$LAMBDA_FUNCTION_NAME \
            S3BucketName=$S3_BUCKET \
      - echo "Deployment complete!"
