#buildspec-deploy.yml
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9  # AWS SAM requires Python
  build:
    commands:
      - echo "Deploying application..."
      - |
        sam deploy \
          --template-file packaged-template.yaml\
          --stack-name $STACK_NAME \
          --s3-bucket $S3_BUCKET \
          --region $REGION \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM \
          --parameter-overrides \
            ApiStageName=$STAGE \
            DynamoDBTableName=$DYNAMODB_TABLE_NAME \
            LambdaFunctionName=$LAMBDA_FUNCTION_NAME \
            S3BucketName=$S3_BUCKET \
            CreatedBy=$CREATED_BY \
            Purpose=$PURPOSE \
            
      - echo "Deployment complete!"
artifacts:
  files:
    - '**/*'
